name: Detect Port Calls
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r worker_detect/requirements.txt
      - env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python worker_detect/detect_events.py
