name: Ingest AIS
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r worker_ingest/requirements.txt
      - env:
          AISS_API_KEY: ${{ secrets.AISS_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python worker_ingest/ingest_aisstream.py
