name: Scrape VesselFinder (4x daily)

on:
  schedule:
    # Runs at 00:13, 06:13, 12:13, and 18:13 UTC every day
    - cron: "13 0,6,12,18 * * *"
  workflow_dispatch: {}    # Allow manual run from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Keep your requirements here
          pip install -r scripts/requirements.txt

      - name: Run VesselFinder scraper
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          S3_BUCKET:    ${{ secrets.S3_BUCKET }}   # optional
        run: |
          python scripts/vf_scrape.py

      - name: Upload CSVs as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: vf-snapshots
          path: data/vf_snapshots/**
